import inquirer
import small_size
from big_cards import big_size

hello_text = 'important:\nsvg file generated by AGE (or some with same structure and column names) is required to make big size nametag'
print(hello_text)
options = [
    inquirer.List(
        'size',
        message='Choose size of your nametags (size 1 = 8 x 6 cm, size 2 = 10 x 145 cm()',
        choices = ['1', '2'],
        default='1'
    ), 
]
answer = inquirer.prompt(options)
size = answer['size']
if(size == '1'): small_size.main()
elif(size == '2'): big_size.main()